keywords = {
    'print': 'prints stuff',
    '#': 'comment',
    '+-*/': 'arithmetic operators',
    '>,=>,==,<,<=': 'comparison operators',
    'variables': 'variables',
    'f""': 'formatted string',
    'int()': 'convert to integer',
    'float()': 'convert to float',
    'input()': 'user input',
    '"string with {}".format("string or variable")': 'another way to format a string',
    "print(variable, end=' ')": 'end a line with a character',
    'print("\n,\t")': 'new line / tab character',
    '""" """': 'docstring',
    'python ex13.py argument': 'script, arg1 = argv',
    'txt = open(filename)': 'open a file',
    'txt.read()': 'read a file',
    'txt.close()': 'close a file',
    'print(open(filename).read())': 'short',
    'python ex16.py filename': 'script, filename = argv',
    "target = open(filename, 'w')": 'target.write(line1)',
    "out_file = open(to_file, 'w')": 'out_file.write(indata)',
    'def my_func(a, b)': 'return a + b',
    'f.seek(0)': 'move cursor to beginning',
    'print(1, f.readline())': 'read first line',
    'variable += 1': 'short for assigning',
}